# GRB preprocessing report

Inspect the cached Swift GRB light curves, compare short and long GRBs, and print one full example from each class.

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

from classes import GRBHDF5Dataset

PROJECT_ROOT = Path.cwd()
H5_FILE = PROJECT_ROOT / "data" / "raw" / "classipygrb" / "swift_balanced_lightcurves.h5"
CLASS_NAMES = {0: "short", 1: "long"}

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 180)
pd.set_option("display.float_format", lambda value: f"{value:.4f}")

In [2]:
def class_label(label: int) -> str:
    return CLASS_NAMES.get(int(label), f"class_{label}")


def as_numpy(dataset: GRBHDF5Dataset) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    x = dataset.x.detach().cpu().numpy()
    labels = np.asarray(dataset.labels, dtype=int)
    t90 = np.asarray(dataset.t90, dtype=float)
    return x, labels, t90


def class_distribution(labels: np.ndarray) -> pd.DataFrame:
    rows = []
    total = labels.size
    for label in sorted(np.unique(labels)):
        count = int((labels == label).sum())
        rows.append(
            {
                "label": int(label),
                "class": class_label(int(label)),
                "count": count,
                "percent": 100.0 * count / total if total else 0.0,
            }
        )
    return pd.DataFrame(rows)


def describe_values(values: np.ndarray) -> dict[str, float]:
    finite = values[np.isfinite(values)]
    if finite.size == 0:
        return {
            "mean": np.nan,
            "std": np.nan,
            "median": np.nan,
            "min": np.nan,
            "q25": np.nan,
            "q75": np.nan,
            "max": np.nan,
        }

    return {
        "mean": float(np.mean(finite)),
        "std": float(np.std(finite)),
        "median": float(np.median(finite)),
        "min": float(np.min(finite)),
        "q25": float(np.percentile(finite, 25)),
        "q75": float(np.percentile(finite, 75)),
        "max": float(np.max(finite)),
    }


def t90_summary(labels: np.ndarray, t90: np.ndarray) -> pd.DataFrame:
    rows = []
    for label in sorted(np.unique(labels)):
        stats = describe_values(t90[labels == label])
        rows.append({"class": class_label(int(label)), **stats})
    return pd.DataFrame(rows)

In [13]:
def overall_signal_summary(x: np.ndarray, labels: np.ndarray) -> pd.DataFrame:
    rows = []
    for label in sorted(np.unique(labels)):
        class_x = x[labels == label]
        rows.append(
            {
                "class": class_label(int(label)),
                "all_values_mean": float(np.mean(class_x)),
                "all_values_std": float(np.std(class_x)),
                "per_grb_mean": float(np.mean(class_x.mean(axis=(1, 2)))),
                "per_grb_peak_mean": float(np.mean(class_x.max(axis=(1, 2)))),
                "per_grb_sum_mean": float(np.mean(class_x.sum(axis=(1, 2)))),
                "zero_fraction": float(np.mean(class_x == 0.0)),
            }
        )
    return pd.DataFrame(rows)


def band_summary(x: np.ndarray, labels: np.ndarray, channel_columns: list[str]) -> pd.DataFrame:
    rows = []
    for label in sorted(np.unique(labels)):
        class_x = x[labels == label]
        for channel_idx, channel_name in enumerate(channel_columns):
            channel_x = class_x[:, :, channel_idx]
            per_grb_mean = channel_x.mean(axis=1)
            per_grb_peak = channel_x.max(axis=1)
            per_grb_sum = channel_x.sum(axis=1)
            rows.append(
                {
                    "class": class_label(int(label)),
                    "band": channel_name,
                    "timepoint_mean": float(np.mean(channel_x)),
                    "timepoint_std": float(np.std(channel_x)),
                    "per_grb_mean_avg": float(np.mean(per_grb_mean)),
                    "per_grb_peak_avg": float(np.mean(per_grb_peak)),
                    "per_grb_sum_avg": float(np.mean(per_grb_sum)),
                    "zero_fraction": float(np.mean(channel_x == 0.0)),
                }
            )
    return pd.DataFrame(rows)


def short_long_difference(bands: pd.DataFrame) -> pd.DataFrame:
    if not {"short", "long"}.issubset(set(bands["class"])):
        return pd.DataFrame()

    numeric_columns = [
        "timepoint_mean",
        "timepoint_std",
        "per_grb_mean_avg",
        "per_grb_peak_avg",
        "per_grb_sum_avg",
        "zero_fraction",
    ]
    short = bands[bands["class"] == "short"].set_index("band")
    long = bands[bands["class"] == "long"].set_index("band")
    rows = []
    for band in short.index.intersection(long.index):
        row = {"band": band}
        for column in numeric_columns:
            short_value = float(short.loc[band, column])
            long_value = float(long.loc[band, column])
            row[f"{column}_long_minus_short"] = long_value - short_value
            row[f"{column}_long_div_short"] = (
                long_value / short_value if not np.isclose(short_value, 0.0) else np.nan
            )
        rows.append(row)
    return pd.DataFrame(rows)

In [4]:
def full_grb_dataframe(
    dataset: GRBHDF5Dataset,
    x: np.ndarray,
    labels: np.ndarray,
    label: int,
) -> tuple[str, float, pd.DataFrame]:
    indices = np.where(labels == label)[0]
    if indices.size == 0:
        raise ValueError(f"No {class_label(label)} GRB found")

    idx = int(indices[0])
    grb = pd.DataFrame(x[idx], columns=dataset.channel_columns)
    grb.insert(0, "time_index", np.arange(len(grb)))
    return dataset.names[idx], dataset.t90[idx], grb

## Load dataset

In [5]:
dataset = GRBHDF5Dataset(H5_FILE)
x, labels, t90 = as_numpy(dataset)

print(f"HDF5 file: {H5_FILE}")
print(f"Loaded GRBs: {len(dataset)}")
print(f"Input shape: {tuple(x.shape)}")
print(f"Channels: {', '.join(dataset.channel_columns)}")
print(f"Label rule: {dataset.label_rule}")
print(f"Cache normalization: {dataset.cache_normalization}")

HDF5 file: /Users/daniele/Desktop/esami mancanti/grb-thesis/Spectral-Evolution-of-a-GRB/data/raw/classipygrb/swift_balanced_lightcurves.h5
Loaded GRBs: 268
Input shape: (268, 256, 4)
Channels: 15-25keV, 25-50keV, 50-100keV, 100-350keV
Label rule: 0 short: T90 <= 2s; 1 long: T90 > 2s
Cache normalization: none; raw resampled light curves

## Class distribution

In [6]:
class_distribution(labels)

   label  class  count  percent
0      0  short    134  50.0000
1      1   long    134  50.0000

## How time, channels, and T90 fit together

- `t90` is one number for the whole GRB. It is the duration used to label the burst as short or long.
- `time_index` is only the row position inside the processed light curve array. It is not T90 and it is not necessarily seconds.
- Each channel/band column is one energy band value at that processed time position.
- The HDF5 file stores a fixed-size tensor, so every GRB has the same number of time rows. Short bursts often have many zero rows because the useful signal is short compared with the fixed length.

In [ ]:
print(f"X shape: {x.shape}")
print("Meaning: (number_of_grbs, processed_time_rows, channels)")
print(f"Number of GRBs: {x.shape[0]}")
print(f"Processed time rows per GRB: {x.shape[1]}")
print(f"Number of channels/bands: {x.shape[2]}")
print(f"Channels: {dataset.channel_columns}")

pd.DataFrame(
    {
        "object": ["t90", "time_index", "channel value"],
        "where_it_lives": ["dataset.t90, one value per GRB", "row index inside X", "X[grb_index, time_index, channel_index]"],
        "meaning": [
            "duration of the burst; used for short/long label",
            "processed row number; not automatically seconds",
            "light-curve value for one band at one processed time row",
        ],
    }
)

In [ ]:
def nonzero_row_summary(grb_df: pd.DataFrame) -> dict[str, int | None]:
    band_cols = [column for column in grb_df.columns if column != "time_index"]
    nonzero_rows = (grb_df[band_cols] != 0).any(axis=1)

    if not nonzero_rows.any():
        first_nonzero = None
        last_nonzero = None
    else:
        nonzero_indices = grb_df.loc[nonzero_rows, "time_index"]
        first_nonzero = int(nonzero_indices.iloc[0])
        last_nonzero = int(nonzero_indices.iloc[-1])

    return {
        "total_rows": int(len(grb_df)),
        "rows_with_any_signal": int(nonzero_rows.sum()),
        "all_zero_rows": int((~nonzero_rows).sum()),
        "first_nonzero_time_index": first_nonzero,
        "last_nonzero_time_index": last_nonzero,
    }


short_name, short_t90, short_grb = full_grb_dataframe(dataset, x, labels, label=0)
long_name, long_t90, long_grb = full_grb_dataframe(dataset, x, labels, label=1)

pd.DataFrame(
    [
        {"class": "short", "name": short_name, "t90": short_t90, **nonzero_row_summary(short_grb)},
        {"class": "long", "name": long_name, "t90": long_t90, **nonzero_row_summary(long_grb)},
    ]
)

In [ ]:
def compact_grb_preview(grb_df: pd.DataFrame, edge_rows: int = 8) -> pd.DataFrame:
    if len(grb_df) <= edge_rows * 2:
        return grb_df

    separator = pd.DataFrame(
        [{column: "..." for column in grb_df.columns}],
        columns=grb_df.columns,
    )
    return pd.concat([grb_df.head(edge_rows), separator, grb_df.tail(edge_rows)], ignore_index=True)


print(f"Short GRB preview: {short_name}, t90={short_t90:.4g}")
display(compact_grb_preview(short_grb))

print(f"Long GRB preview: {long_name}, t90={long_t90:.4g}")
display(compact_grb_preview(long_grb))

## Are the zeros saved in HDF5 or created by ClassiPy?

The zeros you see here are already inside the HDF5 `X` dataset loaded from disk. They are not created by the notebook display.

ClassiPyGRB provides the raw Swift light-curve data. In this project, before saving the HDF5 cache, the light curves were converted to fixed-length arrays. During that preprocessing, short or incomplete curves can be padded with zeros, and missing/non-finite values can also become zeros. So the zeros are saved in HDF5, but they mainly come from the project preprocessing step rather than being a new effect of this notebook.

In [ ]:
zero_report = []
for label in sorted(np.unique(labels)):
    class_x = x[labels == label]
    zero_report.append(
        {
            "class": class_label(int(label)),
            "values_in_h5_X": int(class_x.size),
            "zeros_in_h5_X": int((class_x == 0).sum()),
            "zero_fraction": float((class_x == 0).mean()),
        }
    )

pd.DataFrame(zero_report)

## Full short GRB example

In [7]:
short_name, short_t90, short_grb = full_grb_dataframe(dataset, x, labels, label=0)
print(f"Short GRB: name={short_name}, label=0, t90={short_t90:.4g}")

with pd.option_context("display.max_rows", None):
    display(short_grb)

Short GRB: name=GRB101219A, label=0, t90=0.828

     time_index  15-25keV  25-50keV  50-100keV  100-350keV
0             0   -0.0768   -0.1466     0.0023     -0.0023
1             1   -0.0130    0.0784     0.0265      0.0234
2             2    0.0521    0.0378    -0.0074      0.0185
3             3   -0.0158   -0.0412     0.0420      0.0641
4             4   -0.0638   -0.0031     0.0179     -0.0230
5             5    0.0091    0.0134    -0.0012     -0.0544
6             6    0.0419   -0.0084     0.0181     -0.0301
7             7    0.0279    0.0072     0.0048     -0.0654
8             8    0.0540   -0.0751     0.0516      0.0146
9             9    0.0201    0.0696     0.0811     -0.0015
10           10   -0.0050    0.0176     0.1075     -0.0594
11           11   -0.0816   -0.0168    -0.0463      0.0051
12           12    0.0457    0.0644    -0.0302      0.0540
13           13   -0.0285    0.1047    -0.0341      0.0283
14           14    0.0200    0.0354    -0.0051      0.0924
15           15    0.0277   -0.1044     0.0564     -0.0116
16           16   -0.0154   -0.0415    -0.1038      0.0138
17           17    0.0481    0.0653     0.0400      0.0042
18           18    0.0333    0.0439     0.0140     -0.0189
19           19    0.0043   -0.0071     0.0094     -0.0579
20           20   -0.0085   -0.0013     0.0146     -0.0184
21           21    0.0047    0.0459     0.0239     -0.0144
22           22   -0.0413    0.0075     0.0011      0.0165
23           23    0.0130   -0.0219     0.0005     -0.0077
24           24    0.0185    0.0008     0.0102     -0.0240
25           25    0.0145    0.0007    -0.0068     -0.0012
26           26    0.0251   -0.0191     0.0152      0.0238
27           27    0.0196    0.0206     0.0099      0.0015
28           28    0.0219   -0.0078    -0.0216      0.0012
29           29    0.0026   -0.0045    -0.0100      0.0005
30           30    0.0049   -0.0275     0.0124      0.0136
31           31   -0.0080   -0.0161     0.0028      0.0171
32           32   -0.0010    0.0057    -0.0262     -0.0209
33           33    0.0043   -0.0017    -0.0142      0.0037
34           34    0.0055    0.0015    -0.0135      0.0054
35           35   -0.0092   -0.0035     0.0054      0.0032
36           36   -0.0101    0.0035     0.0065     -0.0052
37           37    0.0065    0.0060     0.0210      0.0032
38           38    0.0308   -0.0266     0.0280      0.0048
39           39   -0.0188   -0.0153     0.0075     -0.0174
40           40   -0.0050    0.0010    -0.0176     -0.0095
41           41   -0.0159    0.0176    -0.0009     -0.0081
42           42    0.0176    0.0253    -0.0019      0.0011
43           43   -0.0542   -0.0086     0.0231     -0.0435
44           44   -0.0119   -0.0085    -0.0144      0.0033
45           45    0.0116   -0.0125    -0.0019      0.0101
46           46    0.0128   -0.0101    -0.0064     -0.0024
47           47    0.0132   -0.0122     0.0067     -0.0059
48           48    0.0158   -0.0061     0.0266      0.0042
49           49    0.0271    0.0129     0.0033     -0.0015
50           50    0.0480    0.0219    -0.0241     -0.0119
51           51    0.0088    0.0120     0.0063     -0.0020
52           52    0.0030    0.0485     0.0300     -0.0211
53           53   -0.0226    0.0146    -0.0122     -0.0023
54           54   -0.0033    0.0086     0.0102     -0.0075
55           55    0.0277    0.0171     0.0265     -0.0002
56           56   -0.0232    0.0064    -0.0101      0.0029
57           57   -0.0334    0.0116     0.0051     -0.0027
58           58   -0.0326   -0.0368    -0.0105     -0.0111
59           59    0.0055    0.0106     0.0315      0.0349
60           60    0.0045    0.0149    -0.0287     -0.0139
61           61   -0.0131   -0.0278     0.0254      0.0101
62           62   -0.0083    0.0096     0.0148      0.0180
63           63   -0.0285   -0.0148    -0.0061      0.0093
64           64   -0.0145   -0.0157    -0.0287     -0.0112
65           65    0.0101   -0.0246    -0.0217      0.0136
66           66   -0.0019   -0.0050    -0.0205     -0.0051
67           67    0.0127   -0.0128    -0.0184      0.0174
68           68   -0.0236    0.0049    -0.0335     -0.0107
69           69    0.0135    0.0168    -0.0099      0.0053
70           70    0.0236   -0.0135    -0.0221     -0.0037
71           71   -0.0148   -0.0062    -0.0184      0.0200
72           72   -0.0404    0.0176     0.0096      0.0119
73           73    0.0041    0.0235    -0.0109     -0.0122
74           74   -0.0023   -0.0017    -0.0108     -0.0091
75           75   -0.0222    0.0142    -0.0375      0.0001
76           76    0.0150   -0.0158    -0.0067     -0.0171
77           77   -0.0043    0.0063    -0.0094     -0.0076
78           78    0.0155    0.0458     0.0037      0.0126
79           79   -0.0177   -0.0311    -0.0172     -0.0060
80           80   -0.0027    0.0040     0.0375      0.0172
81           81    0.0076   -0.0010     0.0232     -0.0099
82           82   -0.0103   -0.0266    -0.0154      0.0177
83           83   -0.0346   -0.0148     0.0474     -0.0095
84           84   -0.0097    0.0319    -0.0111     -0.0240
85           85    0.0075    0.0136     0.0026     -0.0027
86           86   -0.0083   -0.0206     0.0194     -0.0181
87           87    0.0235   -0.0314    -0.0285      0.0024
88           88    0.0189   -0.0011    -0.0066     -0.0159
89           89    0.0211   -0.0278     0.0128     -0.0008
90           90   -0.0013   -0.0109    -0.0047     -0.0033
91           91   -0.0340    0.0031    -0.0023     -0.0230
92           92    0.0153   -0.0074    -0.0197     -0.0103
93           93   -0.0046    0.0197     0.0033     -0.0134
94           94   -0.0270   -0.0429     0.0071      0.0209
95           95    0.0136   -0.0203    -0.0126     -0.0091
96           96    0.0152   -0.0053     0.0044     -0.0070
97           97    0.0029    0.0445     0.0004     -0.0086
98           98   -0.0096   -0.0056     0.0210     -0.0069
99           99    0.0369    0.0365    -0.0204      0.0030
100         100   -0.0191    0.0348     0.0099     -0.0115
101         101   -0.0002    0.0164     0.0370      0.0065
102         102    0.0136    0.0141    -0.0129      0.0183
103         103    0.0113   -0.0376    -0.0084     -0.0193
104         104   -0.0060    0.0198    -0.0158      0.0105
105         105   -0.0082   -0.0359     0.0020      0.0102
106         106    0.0177    0.0024     0.0063      0.0089
107         107    0.0347   -0.0160    -0.0107      0.0024
108         108   -0.0129   -0.0217    -0.0123     -0.0241
109         109    0.0164   -0.0220     0.0311     -0.0001
110         110   -0.0051    0.0007     0.0094      0.0013
111         111   -0.0078   -0.0063     0.0001     -0.0142
112         112    0.0182    0.0023    -0.0109      0.0042
113         113   -0.0186    0.0082     0.0009      0.0271
114         114   -0.0074    0.0178     0.0099     -0.0065
115         115   -0.0562   -0.0170    -0.0232      0.0022
116         116   -0.0070   -0.0092    -0.0043      0.0120
117         117    0.0077   -0.0025    -0.0292     -0.0075
118         118   -0.0087    0.0001     0.0288      0.0294
119         119   -0.0012    0.0092    -0.0021     -0.0059
120         120    0.0163    0.0114     0.0103      0.0107
121         121    0.0063   -0.0116     0.0237      0.0033
122         122    0.0117    0.0006    -0.0083     -0.0002
123         123   -0.0003   -0.0274    -0.0022      0.0238
124         124   -0.0050   -0.0295     0.0095     -0.0177
125         125    0.0215    0.0043    -0.0148     -0.0065
126         126    0.0150    0.0191     0.0430      0.0219
127         127   -0.0124   -0.0019    -0.0193      0.0028
128         128    0.0180    0.0254    -0.0185     -0.0152
129         129    0.0033   -0.0310     0.0081     -0.0115
130         130   -0.0093    0.0084     0.0238      0.0002
131         131    0.0006   -0.0075     0.0049      0.0172
132         132    0.0069   -0.0400    -0.0251     -0.0003
133         133   -0.0110   -0.0023     0.0311     -0.0053
134         134    0.0338   -0.0163    -0.0243      0.0078
135         135   -0.0078   -0.0097    -0.0105      0.0054
136         136    0.0132    0.0207     0.0009     -0.0051
137         137    0.0000   -0.0276    -0.0028      0.0131
138         138   -0.0023   -0.0071    -0.0163     -0.0059
139         139   -0.0040   -0.0602    -0.0238     -0.0096
140         140    0.0003    0.0129     0.0106     -0.0186
141         141    0.0043    0.0215    -0.0161      0.0074
142         142   -0.0026   -0.0006     0.0070      0.0149
143         143    0.0406    0.0103     0.0062      0.0035
144         144    0.0051    0.0062    -0.0093      0.0054
145         145   -0.0355    0.0019     0.0244     -0.0395
146         146    0.0127   -0.0032     0.0253     -0.0108
147         147    0.0372   -0.0179     0.0334     -0.0024
148         148    0.0189   -0.0095    -0.0203      0.0054
149         149   -0.0097    0.0391    -0.0003     -0.0002
150         150    0.0149    0.0089     0.0166     -0.0149
151         151   -0.0004   -0.0045    -0.0138     -0.0041
152         152   -0.0256   -0.0017     0.0113      0.0024
153         153   -0.0002    0.0093    -0.0286      0.0043
154         154   -0.0241    0.0060    -0.0115      0.0166
155         155    0.0168    0.0106    -0.0061      0.0068
156         156   -0.0222    0.0219     0.0167     -0.0017
157         157    0.0234   -0.0258     0.0105     -0.0146
158         158    0.0219   -0.0051    -0.0101     -0.0264
159         159    0.0011    0.0179     0.0274      0.0214
160         160    0.0070   -0.0013    -0.0231     -0.0189
161         161    0.0024   -0.0022     0.0080     -0.0020
162         162   -0.0037    0.0283    -0.0028     -0.0050
163         163   -0.0014    0.0229     0.0184      0.0139
164         164    0.0317   -0.0018    -0.0275     -0.0003
165         165    0.0027   -0.0224     0.0240      0.0119
166         166   -0.0214   -0.0094    -0.0012      0.0196
167         167   -0.0200    0.0182     0.0171      0.0070
168         168   -0.0419    0.0087     0.0056      0.0022
169         169    0.0296   -0.0298    -0.0163      0.0205
170         170   -0.0012    0.0227    -0.0089      0.0146
171         171    0.0055   -0.0264    -0.0071     -0.0046
172         172    0.0054   -0.0253    -0.0220      0.0047
173         173   -0.0112   -0.0089     0.0010      0.0166
174         174   -0.0001   -0.0025     0.0009      0.0216
175         175    0.0307    0.0139     0.0165     -0.0123
176         176    0.0268   -0.0006    -0.0085     -0.0125
177         177   -0.0085   -0.0189     0.0121      0.0310
178         178   -0.0042   -0.0367     0.0262     -0.0222
179         179    0.0025   -0.0138    -0.0074      0.0035
180         180   -0.0172    0.0054    -0.0053      0.0022
181         181   -0.0006    0.0085     0.0041     -0.0026
182         182    0.0289    0.0055     0.0024      0.0132
183         183   -0.0056    0.0033    -0.0019      0.0075
184         184    0.0010   -0.0210     0.0059     -0.0106
185         185    0.0056   -0.0238     0.0292     -0.0160
186         186    0.0066    0.0187     0.0337      0.0148
187         187   -0.0192   -0.0220     0.0024      0.0182
188         188   -0.0108    0.0027    -0.0174      0.0099
189         189   -0.0071    0.0010     0.0142      0.0028
190         190   -0.0265   -0.0086     0.0004     -0.0022
191         191    0.0169    0.0107     0.0244     -0.0034
192         192   -0.0131   -0.0104     0.0359      0.0097
193         193    0.0033   -0.0090    -0.0022     -0.0440
194         194    0.0247    0.0026     0.0233      0.0169
195         195   -0.0137    0.0041    -0.0166      0.0173
196         196   -0.0135   -0.0258     0.0016      0.0044
197         197   -0.0231    0.0119     0.0230      0.0065
198         198   -0.0247    0.0311    -0.0044      0.0064
199         199   -0.0036   -0.0180     0.0106      0.0059
200         200   -0.0088    0.0076     0.0043     -0.0158
201         201   -0.0158   -0.0016    -0.0226     -0.0079
202         202   -0.0001    0.0270     0.0027      0.0084
203         203    0.0103    0.0078     0.0030     -0.0060
204         204    0.0028    0.0087    -0.0320     -0.0119
205         205    0.0018   -0.0050    -0.0159     -0.0004
206         206    0.0080   -0.0281     0.0178     -0.0017
207         207    0.0042   -0.0113     0.0293      0.0049
208         208    0.0133    0.0186    -0.0134      0.0222
209         209   -0.0088   -0.0042    -0.0142     -0.0025
210         210    0.0064   -0.0105    -0.0175     -0.0054
211         211    0.0181   -0.0075    -0.0143     -0.0117
212         212   -0.0074   -0.0268    -0.0263     -0.0144
213         213    0.0144   -0.0029     0.0080     -0.0076
214         214   -0.0136    0.0044     0.0197     -0.0208
215         215   -0.0186   -0.0210     0.0295      0.0154
216         216   -0.0199    0.0087     0.0086      0.0111
217         217   -0.0226   -0.0145     0.0082     -0.0078
218         218   -0.0025    0.0073     0.0141     -0.0199
219         219    0.0542   -0.0145     0.0470     -0.0000
220         220   -0.0260   -0.0041     0.0144      0.0294
221         221    0.0128   -0.0098     0.0167     -0.0126
222         222    0.0281   -0.0032    -0.0212      0.0248
223         223    0.0124    0.0087    -0.0079      0.0049
224         224    0.0161    0.0119    -0.0097      0.0060
225         225    0.0199    0.0150    -0.0115      0.0071
226         226    0.0236    0.0182    -0.0133      0.0082
227         227    0.0274    0.0213    -0.0151      0.0093
228         228    0.0311    0.0245    -0.0169      0.0104
229         229    0.0349    0.0277    -0.0188      0.0115
230         230    0.0386    0.0308    -0.0206      0.0126
231         231    0.0424    0.0340    -0.0224      0.0137
232         232    0.0461    0.0371    -0.0242      0.0148
233         233    0.0286   -0.0265    -0.0009      0.0348
234         234    0.0216   -0.0372     0.0510     -0.0032
235         235    0.0077    0.1070    -0.0212     -0.0013
236         236    0.0000    0.0000     0.0000      0.0000
237         237    0.0000    0.0000     0.0000      0.0000
238         238    0.0000    0.0000     0.0000      0.0000
239         239    0.0000    0.0000     0.0000      0.0000
240         240    0.0000    0.0000     0.0000      0.0000
241         241    0.0000    0.0000     0.0000      0.0000
242         242    0.0000    0.0000     0.0000      0.0000
243         243    0.0000    0.0000     0.0000      0.0000
244         244    0.0000    0.0000     0.0000      0.0000
245         245    0.0000    0.0000     0.0000      0.0000
246         246    0.0000    0.0000     0.0000      0.0000
247         247    0.0000    0.0000     0.0000      0.0000
248         248    0.0000    0.0000     0.0000      0.0000
249         249    0.0000    0.0000     0.0000      0.0000
250         250    0.0000    0.0000     0.0000      0.0000
251         251    0.0000    0.0000     0.0000      0.0000
252         252    0.0000    0.0000     0.0000      0.0000
253         253    0.0000    0.0000     0.0000      0.0000
254         254    0.0000    0.0000     0.0000      0.0000
255         255    0.0000    0.0000     0.0000      0.0000

## Full long GRB example

In [8]:
long_name, long_t90, long_grb = full_grb_dataframe(dataset, x, labels, label=1)
print(f"Long GRB: name={long_name}, label=1, t90={long_t90:.4g}")

with pd.option_context("display.max_rows", None):
    display(long_grb)

Long GRB: name=GRB180626A, label=1, t90=30.1

     time_index  15-25keV  25-50keV  50-100keV  100-350keV
0             0    0.0054   -0.0199     0.0126     -0.0294
1             1   -0.0271   -0.0021     0.0256      0.0286
2             2    0.0049   -0.0508    -0.0290     -0.0013
3             3   -0.0053    0.0028    -0.0198      0.0138
4             4   -0.0221   -0.0008     0.0171     -0.0373
5             5   -0.0505    0.0266     0.0069      0.0017
6             6    0.0448   -0.0395    -0.0390      0.0384
7             7    0.0304   -0.0385    -0.0069      0.0096
8             8   -0.0002    0.0363     0.0046      0.0199
9             9    0.0237   -0.0328    -0.0236      0.0108
10           10    0.0011   -0.0173     0.0106     -0.0238
11           11    0.0079    0.0260    -0.0108     -0.0390
12           12   -0.0186   -0.0666    -0.0243      0.0135
13           13    0.0278    0.0120     0.0469     -0.0046
14           14    0.0072    0.0750    -0.0562     -0.0293
15           15   -0.0973   -0.0147     0.0181     -0.0215
16           16    0.0256   -0.1082    -0.0498      0.0254
17           17    0.0460    0.0480    -0.0229     -0.0680
18           18   -0.0224   -0.0290    -0.0002      0.0365
19           19    0.0464   -0.0131    -0.0093      0.0145
20           20   -0.0789   -0.0530     0.0102     -0.0357
21           21    0.0257    0.0100     0.0477      0.0124
22           22   -0.0109    0.0113     0.0216     -0.0341
23           23   -0.0562   -0.0058    -0.0031      0.0418
24           24    0.0045   -0.0830    -0.0409     -0.0260
25           25   -0.0329    0.0271    -0.0115      0.0489
26           26    0.0131   -0.0154    -0.0066     -0.0081
27           27   -0.0268   -0.0133     0.0191     -0.0041
28           28   -0.0032    0.0062     0.0188     -0.0268
29           29   -0.0063    0.0642     0.0497     -0.0599
30           30    0.0060   -0.0092    -0.0262     -0.0252
31           31   -0.0184    0.0266    -0.0213     -0.0634
32           32   -0.0136    0.0274    -0.0115      0.0469
33           33   -0.0333    0.0570    -0.0419      0.0195
34           34   -0.0524    0.0553    -0.0325      0.0031
35           35    0.0050   -0.0503    -0.0301      0.0662
36           36    0.0092    0.0193    -0.0307      0.0071
37           37    0.0353   -0.0351    -0.0085      0.0645
38           38   -0.0078    0.0262     0.0159     -0.0446
39           39    0.0679   -0.0283     0.0421      0.0156
40           40   -0.0796   -0.0016     0.0280      0.0313
41           41   -0.0117    0.0706     0.0360     -0.0464
42           42    0.0316   -0.0323    -0.0274     -0.0008
43           43   -0.0165    0.0459    -0.0062      0.0075
44           44   -0.0176    0.0694    -0.0040      0.0405
45           45   -0.0391   -0.0479     0.0020     -0.0035
46           46    0.0011   -0.0145     0.0222     -0.0133
47           47   -0.0418    0.0310     0.0203      0.0212
48           48   -0.0382   -0.0273    -0.0448      0.0136
49           49    0.0009    0.0872     0.0378      0.0255
50           50    0.1041    0.2023     0.1424      0.0294
51           51    0.1640    0.1637     0.0308      0.0099
52           52    0.1596    0.0536     0.0622      0.0046
53           53    0.0600    0.1200     0.1094     -0.0110
54           54    0.1412    0.0450     0.0731     -0.0149
55           55    0.0389    0.0033     0.0520      0.0029
56           56    0.0365    0.0646    -0.0183     -0.0169
57           57   -0.0093   -0.0267     0.0199     -0.0075
58           58   -0.0038   -0.0331     0.0384     -0.0057
59           59    0.0086    0.0430    -0.0076     -0.0005
60           60   -0.0148   -0.0503    -0.0551      0.0034
61           61    0.0130    0.0219     0.0385     -0.0287
62           62   -0.0170   -0.0184    -0.0011      0.0191
63           63    0.0037   -0.0096     0.0034      0.0082
64           64   -0.0187    0.0129    -0.0125      0.0090
65           65   -0.0084   -0.0364     0.0122      0.0091
66           66   -0.0267   -0.0299    -0.0213     -0.0052
67           67   -0.0070   -0.0153    -0.0060     -0.0087
68           68    0.0068    0.0112    -0.0205      0.0189
69           69   -0.0184    0.0183    -0.0276      0.0294
70           70   -0.0147    0.0169     0.0039      0.0038
71           71    0.0174   -0.0201     0.0271      0.0084
72           72   -0.0558    0.0093     0.0129      0.0248
73           73   -0.0145   -0.0119     0.0056     -0.0074
74           74    0.0361   -0.0213    -0.0125     -0.0055
75           75    0.0279   -0.0271     0.0105      0.0283
76           76    0.0072   -0.0187    -0.0077      0.0015
77           77    0.0012   -0.0213    -0.0078      0.0092
78           78   -0.0172    0.0260    -0.0046     -0.0057
79           79    0.0205   -0.0088    -0.0129      0.0067
80           80    0.0182   -0.0058    -0.0213     -0.0199
81           81   -0.0023    0.0331     0.0168     -0.0166
82           82    0.0161   -0.0254     0.0191     -0.0022
83           83    0.0225   -0.0068     0.0034      0.0142
84           84   -0.0157    0.0228    -0.0061      0.0207
85           85   -0.0190    0.0196     0.0123     -0.0032
86           86   -0.0316    0.0325     0.0029     -0.0005
87           87    0.0210    0.0034    -0.0128     -0.0060
88           88   -0.0019   -0.0285    -0.0067     -0.0189
89           89    0.0214    0.0067     0.0441      0.0210
90           90   -0.0105    0.0320    -0.0134     -0.0057
91           91    0.0370   -0.0189     0.0074     -0.0131
92           92    0.0270    0.0042    -0.0161      0.0017
93           93   -0.0201    0.0097    -0.0040      0.0027
94           94   -0.0084    0.0254     0.0107      0.0175
95           95   -0.0144    0.0022    -0.0341     -0.0024
96           96   -0.0130    0.0003     0.0245     -0.0062
97           97    0.0212   -0.0413    -0.0051      0.0173
98           98   -0.0073    0.0350    -0.0065     -0.0100
99           99   -0.0043    0.0298     0.0186     -0.0156
100         100    0.0081    0.0100     0.0013      0.0047
101         101   -0.0148    0.0151     0.0009     -0.0098
102         102    0.0026   -0.0016     0.0106      0.0057
103         103   -0.0179    0.0159    -0.0099      0.0143
104         104    0.0144    0.0035     0.0324      0.0062
105         105   -0.0210   -0.0076     0.0058      0.0019
106         106   -0.0327    0.0383     0.0240     -0.0015
107         107    0.0183   -0.0057    -0.0268     -0.0096
108         108   -0.0100    0.0095    -0.0415      0.0069
109         109   -0.0213    0.0066    -0.0134      0.0202
110         110   -0.0006    0.0031     0.0108      0.0025
111         111    0.0383    0.0432    -0.0037      0.0165
112         112   -0.0216    0.0332     0.0108      0.0164
113         113    0.0021    0.0355    -0.0364      0.0044
114         114   -0.0341   -0.0056     0.0088     -0.0180
115         115   -0.0043    0.0191    -0.0013      0.0018
116         116   -0.0045    0.0158    -0.0066     -0.0220
117         117   -0.0061   -0.0063     0.0096     -0.0077
118         118   -0.0084    0.0036     0.0301      0.0106
119         119    0.0129    0.0243     0.0173      0.0131
120         120   -0.0348   -0.0188    -0.0108     -0.0321
121         121   -0.0226   -0.0183    -0.0168     -0.0162
122         122    0.0032    0.0095    -0.0201     -0.0095
123         123   -0.0208    0.0003    -0.0050     -0.0091
124         124   -0.0132   -0.0192    -0.0132     -0.0017
125         125    0.0208   -0.0019    -0.0042      0.0143
126         126   -0.0065    0.0320    -0.0011      0.0062
127         127    0.0069    0.0027     0.0125      0.0095
128         128   -0.0065   -0.0338    -0.0193     -0.0125
129         129   -0.0000    0.0098    -0.0098      0.0096
130         130    0.0104    0.0065    -0.0222     -0.0043
131         131   -0.0257    0.0263    -0.0179      0.0249
132         132   -0.0153   -0.0056     0.0005     -0.0018
133         133    0.0042    0.0209    -0.0018      0.0060
134         134   -0.0005   -0.0187    -0.0024     -0.0079
135         135   -0.0266    0.0025    -0.0163      0.0187
136         136    0.0015    0.0082     0.0170     -0.0042
137         137    0.0003    0.0218    -0.0064     -0.0076
138         138   -0.0217   -0.0098     0.0015     -0.0054
139         139    0.0038   -0.0095     0.0040     -0.0181
140         140   -0.0243   -0.0042     0.0036      0.0091
141         141   -0.0286    0.0130     0.0043      0.0076
142         142    0.0095    0.0264    -0.0160      0.0069
143         143    0.0131    0.0315     0.0119     -0.0211
144         144   -0.0254   -0.0012    -0.0372     -0.0166
145         145    0.0071   -0.0092     0.0112     -0.0031
146         146   -0.0332   -0.0050    -0.0162     -0.0178
147         147   -0.0060   -0.0111     0.0094      0.0039
148         148   -0.0307   -0.0050    -0.0254      0.0065
149         149   -0.0105    0.0122     0.0058      0.0099
150         150    0.0477   -0.0023    -0.0028     -0.0144
151         151    0.0004    0.0072     0.0224      0.0129
152         152    0.0079    0.0267     0.0241     -0.0480
153         153   -0.0029    0.0118     0.0007     -0.0224
154         154    0.0123   -0.0193    -0.0068     -0.0035
155         155    0.0027    0.0084     0.0034      0.0297
156         156   -0.0305    0.0082    -0.0033      0.0076
157         157    0.0049   -0.0187    -0.0123     -0.0113
158         158   -0.0250    0.0174     0.0218     -0.0073
159         159   -0.0155   -0.0100     0.0271     -0.0099
160         160    0.0186    0.0099     0.0436      0.0235
161         161    0.0074    0.0165     0.0118      0.0023
162         162    0.0112    0.0112     0.0091     -0.0135
163         163    0.0221   -0.0148    -0.0000     -0.0070
164         164    0.0103   -0.0150    -0.0222      0.0095
165         165   -0.0197   -0.0333    -0.0118     -0.0128
166         166    0.0004   -0.0047    -0.0063      0.0247
167         167   -0.0013   -0.0369    -0.0039     -0.0190
168         168   -0.0193   -0.0241    -0.0094      0.0302
169         169    0.0283    0.0212    -0.0129      0.0370
170         170    0.0019   -0.0080    -0.0087      0.0024
171         171    0.0041   -0.0223    -0.0124      0.0113
172         172    0.0143    0.0307     0.0077      0.0002
173         173    0.0160   -0.0167     0.0211      0.0107
174         174    0.0182    0.0297     0.0202     -0.0053
175         175    0.0090    0.0058    -0.0222      0.0119
176         176    0.0035    0.0082    -0.0223      0.0015
177         177   -0.0093   -0.0085    -0.0018      0.0140
178         178   -0.0145   -0.0023     0.0021      0.0138
179         179    0.0138   -0.0117     0.0087      0.0069
180         180   -0.0398    0.0356    -0.0185      0.0167
181         181   -0.0103    0.0260    -0.0012     -0.0012
182         182    0.0241   -0.0030    -0.0287     -0.0179
183         183    0.0168    0.0014     0.0109      0.0195
184         184   -0.0026   -0.0188     0.0224     -0.0077
185         185    0.0074    0.0247     0.0054     -0.0278
186         186   -0.0278   -0.0259     0.0240     -0.0132
187         187   -0.0074   -0.0159     0.0081     -0.0021
188         188    0.0271    0.0112    -0.0058     -0.0072
189         189   -0.0220    0.0061     0.0125      0.0096
190         190    0.0305    0.0004     0.0122      0.0059
191         191   -0.0294    0.0124    -0.0318     -0.0128
192         192    0.0406   -0.0053     0.0084      0.0330
193         193   -0.0001    0.0055    -0.0033     -0.0077
194         194    0.0057    0.0196     0.0019     -0.0132
195         195   -0.0204   -0.0017    -0.0072     -0.0070
196         196   -0.0163   -0.0194     0.0092      0.0256
197         197   -0.0277    0.0003     0.0113     -0.0044
198         198    0.0076    0.0466     0.0160     -0.0146
199         199    0.0085    0.0131     0.0094     -0.0086
200         200    0.0154   -0.0202    -0.0261      0.0025
201         201    0.0201   -0.0245    -0.0141      0.0170
202         202    0.0167    0.0068     0.0176     -0.0134
203         203   -0.0227    0.0153    -0.0148      0.0116
204         204    0.0054   -0.0216    -0.0390     -0.0079
205         205    0.0365   -0.0008    -0.0145     -0.0128
206         206   -0.0057   -0.0026     0.0026     -0.0019
207         207    0.0092   -0.0159     0.0029     -0.0236
208         208    0.0065    0.0176    -0.0199      0.0321
209         209   -0.0432    0.0089     0.0052     -0.0052
210         210   -0.0099   -0.0082     0.0159     -0.0191
211         211    0.0112   -0.0143    -0.0013      0.0033
212         212    0.0095    0.0553     0.0235      0.0045
213         213    0.0393    0.0136     0.0301      0.0325
214         214    0.0187    0.0295    -0.0143     -0.0029
215         215    0.0037   -0.0129     0.0124      0.0080
216         216   -0.0293   -0.0064    -0.0047     -0.0071
217         217    0.0068   -0.0048    -0.0173     -0.0075
218         218   -0.0090    0.0058    -0.0090     -0.0272
219         219    0.0002    0.0155    -0.0119     -0.0040
220         220   -0.0118    0.0147    -0.0050      0.0276
221         221    0.0195    0.0316     0.0045      0.0125
222         222   -0.0012    0.0104     0.0076      0.0133
223         223    0.0320   -0.0231    -0.0151      0.0126
224         224    0.0147    0.0188    -0.0105      0.0107
225         225    0.0156    0.0019     0.0286     -0.0054
226         226   -0.0045   -0.0121    -0.0114      0.0150
227         227    0.0041   -0.0022    -0.0298     -0.0030
228         228   -0.0077    0.0106    -0.0146     -0.0238
229         229    0.0442   -0.0021    -0.0094      0.0166
230         230   -0.0147    0.0046     0.0115      0.0014
231         231    0.0111   -0.0290    -0.0055     -0.0011
232         232    0.0407    0.0304    -0.0379      0.0130
233         233    0.0055   -0.0124    -0.0103      0.0018
234         234    0.0050    0.0117     0.0264     -0.0183
235         235    0.0145   -0.0069     0.0193      0.0121
236         236    0.0081    0.0137     0.0101      0.0048
237         237   -0.0271    0.0053     0.0130      0.0177
238         238    0.0422   -0.0073    -0.0150     -0.0042
239         239    0.0100    0.0064    -0.0157      0.0084
240         240   -0.0047    0.0077     0.0180      0.0058
241         241   -0.0041   -0.0059    -0.0176     -0.0143
242         242    0.0385    0.0143     0.0067      0.0139
243         243    0.0007   -0.0125     0.0029      0.0052
244         244   -0.0153   -0.0064     0.0029      0.0168
245         245    0.0426   -0.0175    -0.0057     -0.0149
246         246   -0.0259    0.0018    -0.0121     -0.0118
247         247   -0.0103   -0.0040    -0.0187     -0.0121
248         248   -0.0013   -0.0052     0.0197     -0.0126
249         249    0.0003    0.0365     0.0115     -0.0340
250         250   -0.0084    0.0178    -0.0240      0.0051
251         251    0.0030   -0.0208    -0.0252     -0.0106
252         252    0.0014    0.0250    -0.0145     -0.0091
253         253    0.0044    0.0008    -0.0103     -0.0034
254         254   -0.0081   -0.0314     0.0106      0.0070
255         255   -0.0406   -0.0564    -0.0410      0.0034

## T90 summary by class

In [9]:
t90_summary(labels, t90)

   class    mean     std  median    min     q25     q75      max
0  short  0.5541  0.4839  0.3840 0.0120  0.1800  0.8250   2.0000
1   long 79.8882 94.2413 44.7980 2.0920 17.8240 99.1700 600.0080

## Overall light-curve summary by class

In [10]:
overall_signal_summary(x, labels)

   class  all_values_mean  all_values_std  per_grb_mean  per_grb_peak_mean  per_grb_sum_mean  zero_fraction
0  short           0.0005          0.0227        0.0005             0.1156            0.5148         0.1200
1   long           0.0021          0.0290        0.0021             0.1681            2.1908         0.1467

## Average values across bands by class

In [11]:
bands = band_summary(x, labels, dataset.channel_columns)
bands

   class        band  timepoint_mean  timepoint_std  per_grb_mean_avg  per_grb_peak_avg  per_grb_sum_avg  zero_fraction
0  short    15-25keV          0.0001         0.0233            0.0001            0.0806           0.0131         0.1200
1  short    25-50keV          0.0008         0.0249            0.0008            0.0969           0.2005         0.1200
2  short   50-100keV          0.0009         0.0229            0.0009            0.0915           0.2184         0.1200
3  short  100-350keV          0.0003         0.0193            0.0003            0.0668           0.0827         0.1200
4   long    15-25keV          0.0022         0.0283            0.0022            0.1175           0.5539         0.1467
5   long    25-50keV          0.0032         0.0337            0.0032            0.1503           0.8112         0.1467
6   long   50-100keV          0.0027         0.0312            0.0027            0.1354           0.7015         0.1467
7   long  100-350keV          0.0005         0.0210            0.0005            0.0808           0.1241         0.1467

## Long versus short differences by band

In [12]:
short_long_difference(bands)

,band,timepoint_mean_long_minus_short,timepoint_mean_long_div_short,timepoint_std_long_minus_short,timepoint_std_long_div_short,per_grb_mean_avg_long_minus_short,per_grb_mean_avg_long_div_short,per_grb_peak_avg_long_minus_short,per_grb_peak_avg_long_div_short,per_grb_sum_avg_long_minus_short,per_grb_sum_avg_long_div_short,zero_fraction_long_minus_short,zero_fraction_long_div_short
0,15-25keV,0.0021,42.3769,0.0050,1.2166,0.0021,42.3769,0.0369,1.4583,0.5409,42.3769,0.0267,1.2225
1,25-50keV,0.0024,4.0453,0.0088,1.3543,0.0024,4.0453,0.0534,1.5508,0.6107,4.0453,0.0267,1.2225
2,50-100keV,0.0019,3.2115,0.0083,1.3616,0.0019,3.2115,0.0439,1.4803,0.4831,3.2115,0.0267,1.2225
3,100-350keV,0.0002,1.4993,0.0017,1.0891,0.0002,1.4993,0.0141,1.2110,0.0413,1.4993,0.0267,1.2222