# GRB preprocessing report

Inspect the cached Swift GRB light curves, compare short and long GRBs, and print one full example from each class.

In [75]:
from pathlib import Path

import numpy as np
import pandas as pd

from classes import GRBHDF5Dataset

PROJECT_ROOT = Path.cwd()
H5_FILE = PROJECT_ROOT / "data" / "processed" / "classipygrb" / "swift.hd5"
CLASS_NAMES = {0: "short", 1: "long"}

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 180)
pd.set_option("display.float_format", lambda value: f"{value:.4f}")

In [76]:
def class_label(label: int) -> str:
    return CLASS_NAMES.get(int(label), f"class_{label}")


def as_numpy(dataset: GRBHDF5Dataset) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    x = dataset.x.detach().cpu().numpy()
    labels = np.asarray(dataset.labels, dtype=int)
    t90 = np.asarray(dataset.t90, dtype=float)
    return x, labels, t90


def class_distribution(labels: np.ndarray) -> pd.DataFrame:
    rows = []
    total = labels.size
    for label in sorted(np.unique(labels)):
        count = int((labels == label).sum())
        rows.append(
            {
                "label": int(label),
                "class": class_label(int(label)),
                "count": count,
                "percent": 100.0 * count / total if total else 0.0,
            }
        )
    return pd.DataFrame(rows)


def describe_values(values: np.ndarray) -> dict[str, float]:
    finite = values[np.isfinite(values)]
    if finite.size == 0:
        return {
            "mean": np.nan,
            "std": np.nan,
            "median": np.nan,
            "min": np.nan,
            "q25": np.nan,
            "q75": np.nan,
            "max": np.nan,
        }

    return {
        "mean": float(np.mean(finite)),
        "std": float(np.std(finite)),
        "median": float(np.median(finite)),
        "min": float(np.min(finite)),
        "q25": float(np.percentile(finite, 25)),
        "q75": float(np.percentile(finite, 75)),
        "max": float(np.max(finite)),
    }


def t90_summary(labels: np.ndarray, t90: np.ndarray) -> pd.DataFrame:
    rows = []
    for label in sorted(np.unique(labels)):
        stats = describe_values(t90[labels == label])
        rows.append({"class": class_label(int(label)), **stats})
    return pd.DataFrame(rows)

In [77]:
def overall_signal_summary(x: np.ndarray, labels: np.ndarray) -> pd.DataFrame:
    rows = []
    for label in sorted(np.unique(labels)):
        class_x = x[labels == label]
        rows.append(
            {
                "class": class_label(int(label)),
                "all_values_mean": float(np.mean(class_x)),
                "all_values_std": float(np.std(class_x)),
                "per_grb_mean": float(np.mean(class_x.mean(axis=(1, 2)))),
                "per_grb_peak_mean": float(np.mean(class_x.max(axis=(1, 2)))),
                "per_grb_sum_mean": float(np.mean(class_x.sum(axis=(1, 2)))),
                "zero_fraction": float(np.mean(class_x == 0.0)),
            }
        )
    return pd.DataFrame(rows)


def band_summary(x: np.ndarray, labels: np.ndarray, channel_columns: list[str]) -> pd.DataFrame:
    rows = []
    for label in sorted(np.unique(labels)):
        class_x = x[labels == label]
        for channel_idx, channel_name in enumerate(channel_columns):
            channel_x = class_x[:, :, channel_idx]
            per_grb_mean = channel_x.mean(axis=1)
            per_grb_peak = channel_x.max(axis=1)
            per_grb_sum = channel_x.sum(axis=1)
            rows.append(
                {
                    "class": class_label(int(label)),
                    "band": channel_name,
                    "timepoint_mean": float(np.mean(channel_x)),
                    "timepoint_std": float(np.std(channel_x)),
                    "per_grb_mean_avg": float(np.mean(per_grb_mean)),
                    "per_grb_peak_avg": float(np.mean(per_grb_peak)),
                    "per_grb_sum_avg": float(np.mean(per_grb_sum)),
                    "zero_fraction": float(np.mean(channel_x == 0.0)),
                }
            )
    return pd.DataFrame(rows)


def short_long_difference(bands: pd.DataFrame) -> pd.DataFrame:
    if not {"short", "long"}.issubset(set(bands["class"])):
        return pd.DataFrame()

    numeric_columns = [
        "timepoint_mean",
        "timepoint_std",
        "per_grb_mean_avg",
        "per_grb_peak_avg",
        "per_grb_sum_avg",
        "zero_fraction",
    ]
    short = bands[bands["class"] == "short"].set_index("band")
    long = bands[bands["class"] == "long"].set_index("band")
    rows = []
    for band in short.index.intersection(long.index):
        row = {"band": band}
        for column in numeric_columns:
            short_value = float(short.loc[band, column])
            long_value = float(long.loc[band, column])
            row[f"{column}_long_minus_short"] = long_value - short_value
            row[f"{column}_long_div_short"] = (
                long_value / short_value if not np.isclose(short_value, 0.0) else np.nan
            )
        rows.append(row)
    return pd.DataFrame(rows)

In [78]:
def full_grb_dataframe(
    dataset: GRBHDF5Dataset,
    x: np.ndarray,
    labels: np.ndarray,
    label: int,
) -> tuple[str, float, pd.DataFrame]:
    indices = np.where(labels == label)[0]
    if indices.size == 0:
        raise ValueError(f"No {class_label(label)} GRB found")

    idx = int(indices[0])
    grb = pd.DataFrame(x[idx], columns=dataset.channel_columns)
    grb.insert(0, "time_index", np.arange(len(grb)))
    return dataset.names[idx], dataset.t90[idx], grb

## Load dataset

In [79]:
dataset = GRBHDF5Dataset(H5_FILE)
x, labels, t90 = as_numpy(dataset)

print(f"HDF5 file: {H5_FILE}")
print(f"Loaded GRBs: {len(dataset)}")
print(f"Input shape: {tuple(x.shape)}")
print(f"Channels: {', '.join(dataset.channel_columns)}")
print(f"Label rule: {dataset.label_rule}")

HDF5 file: /Users/daniele/Desktop/esami mancanti/grb-thesis/Spectral-Evolution-of-a-GRB/data/processed/classipygrb/swift.hd5
Loaded GRBs: 268
Input shape: (268, 313, 4)
Channels: 15-25keV, 25-50keV, 50-100keV, 100-350keV
Label rule: 0 short, 1 long

## Class distribution

In [80]:
class_distribution(labels)

   label  class  count  percent
0      0  short    134  50.0000
1      1   long    134  50.0000

## How time, channels, and T90 fit together

- `t90` is one number for the whole GRB. It is the duration used to label the burst as short or long.
- `time_index` is only the row position inside the processed light curve array. It is not T90 and it is not necessarily seconds.
- Each channel/band column is one energy band value at that processed time position.
- The HDF5 file stores a fixed-size tensor, so every GRB has the same number of time rows. Short bursts often have many zero rows because the useful signal is short compared with the fixed length.

In [81]:
print(f"X shape: {x.shape}")
print("Meaning: (number_of_grbs, processed_time_rows, channels)")
print(f"Number of GRBs: {x.shape[0]}")
print(f"Processed time rows per GRB: {x.shape[1]}")
print(f"Number of channels/bands: {x.shape[2]}")
print(f"Channels: {dataset.channel_columns}")

pd.DataFrame(
    {
        "object": ["t90", "time_index", "channel value"],
        "where_it_lives": ["dataset.t90, one value per GRB", "row index inside X", "X[grb_index, time_index, channel_index]"],
        "meaning": [
            "duration of the burst; used for short/long label",
            "processed row number; not automatically seconds",
            "light-curve value for one band at one processed time row",
        ],
    }
)

X shape: (268, 313, 4)
Meaning: (number_of_grbs, processed_time_rows, channels)
Number of GRBs: 268
Processed time rows per GRB: 313
Number of channels/bands: 4
Channels: ['15-25keV', '25-50keV', '50-100keV', '100-350keV']

          object                           where_it_lives                                            meaning
0            t90           dataset.t90, one value per GRB   duration of the burst; used for short/long label
1     time_index                       row index inside X    processed row number; not automatically seconds
2  channel value  X[grb_index, time_index, channel_index]  light-curve value for one band at one processe...

In [82]:
def nonzero_row_summary(grb_df: pd.DataFrame) -> dict[str, int | None]:
    band_cols = [column for column in grb_df.columns if column != "time_index"]
    nonzero_rows = (grb_df[band_cols] != 0).any(axis=1)

    if not nonzero_rows.any():
        first_nonzero = None
        last_nonzero = None
    else:
        nonzero_indices = grb_df.loc[nonzero_rows, "time_index"]
        first_nonzero = int(nonzero_indices.iloc[0])
        last_nonzero = int(nonzero_indices.iloc[-1])

    return {
        "total_rows": int(len(grb_df)),
        "rows_with_any_signal": int(nonzero_rows.sum()),
        "all_zero_rows": int((~nonzero_rows).sum()),
        "first_nonzero_time_index": first_nonzero,
        "last_nonzero_time_index": last_nonzero,
    }


short_name, short_t90, short_grb = full_grb_dataframe(dataset, x, labels, label=0)
long_name, long_t90, long_grb = full_grb_dataframe(dataset, x, labels, label=1)

pd.DataFrame(
    [
        {"class": "short", "name": short_name, "t90": short_t90, **nonzero_row_summary(short_grb)},
        {"class": "long", "name": long_name, "t90": long_t90, **nonzero_row_summary(long_grb)},
    ]
)

   class       name    t90  total_rows  rows_with_any_signal  all_zero_rows  first_nonzero_time_index  last_nonzero_time_index
0  short  GRB050202 0.1120         313                     3            310                         0                        2
1   long  GRB041217 5.6680         313                   177            136                         0                      176

In [83]:
def compact_grb_preview(grb_df: pd.DataFrame, edge_rows: int = 8) -> pd.DataFrame:
    if len(grb_df) <= edge_rows * 2:
        return grb_df

    separator = pd.DataFrame(
        [{column: "..." for column in grb_df.columns}],
        columns=grb_df.columns,
    )
    return pd.concat([grb_df.head(edge_rows), separator, grb_df.tail(edge_rows)], ignore_index=True)


print(f"Short GRB preview: {short_name}, t90={short_t90:.4g}")
display(compact_grb_preview(short_grb))

print(f"Long GRB preview: {long_name}, t90={long_t90:.4g}")
display(compact_grb_preview(long_grb))

Short GRB preview: GRB050202, t90=0.112

   time_index 15-25keV 25-50keV 50-100keV 100-350keV
0           0  -0.0204   0.0219    0.0180    -0.0119
1           1   0.0998   0.1877    0.1782     0.0274
2           2   0.0416   0.1169    0.0870     0.0334
3           3   0.0000   0.0000    0.0000     0.0000
4           4   0.0000   0.0000    0.0000     0.0000
5           5   0.0000   0.0000    0.0000     0.0000
6           6   0.0000   0.0000    0.0000     0.0000
7           7   0.0000   0.0000    0.0000     0.0000
8         ...      ...      ...       ...        ...
9         305   0.0000   0.0000    0.0000     0.0000
10        306   0.0000   0.0000    0.0000     0.0000
11        307   0.0000   0.0000    0.0000     0.0000
12        308   0.0000   0.0000    0.0000     0.0000
13        309   0.0000   0.0000    0.0000     0.0000
14        310   0.0000   0.0000    0.0000     0.0000
15        311   0.0000   0.0000    0.0000     0.0000
16        312   0.0000   0.0000    0.0000     0.0000

Long GRB preview: GRB041217, t90=5.668

   time_index 15-25keV 25-50keV 50-100keV 100-350keV
0           0  -0.0350   0.0133   -0.0239    -0.0900
1           1   0.0201   0.0093    0.0516    -0.0400
2           2  -0.0378   0.0997    0.1070     0.0871
3           3   0.0406   0.0368   -0.0109     0.0262
4           4   0.0477   0.0592    0.0537     0.0237
5           5  -0.1250   0.1725   -0.1297     0.0208
6           6   0.0488   0.0504    0.0733     0.0359
7           7  -0.1107   0.0795    0.1080    -0.0065
8         ...      ...      ...       ...        ...
9         305   0.0000   0.0000    0.0000     0.0000
10        306   0.0000   0.0000    0.0000     0.0000
11        307   0.0000   0.0000    0.0000     0.0000
12        308   0.0000   0.0000    0.0000     0.0000
13        309   0.0000   0.0000    0.0000     0.0000
14        310   0.0000   0.0000    0.0000     0.0000
15        311   0.0000   0.0000    0.0000     0.0000
16        312   0.0000   0.0000    0.0000     0.0000

## Are the zeros saved in HDF5 or created by ClassiPy?

The zeros you see here are already inside the HDF5 `X` dataset loaded from disk. They are not created by the notebook display.

ClassiPyGRB provides the raw Swift light-curve data. In this project, before saving the HDF5 cache, the light curves were converted to fixed-length arrays. During that preprocessing, short or incomplete curves can be padded with zeros, and missing/non-finite values can also become zeros. So the zeros are saved in HDF5, but they mainly come from the project preprocessing step rather than being a new effect of this notebook.

In [84]:
zero_report = []
for label in sorted(np.unique(labels)):
    class_x = x[labels == label]
    zero_report.append(
        {
            "class": class_label(int(label)),
            "values_in_h5_X": int(class_x.size),
            "zeros_in_h5_X": int((class_x == 0).sum()),
            "zero_fraction": float((class_x == 0).mean()),
        }
    )

pd.DataFrame(zero_report)

   class  values_in_h5_X  zeros_in_h5_X  zero_fraction
0  short          167768         158885         0.9471
1   long          167768          86838         0.5176

## Full short GRB example

In [85]:
short_name, short_t90, short_grb = full_grb_dataframe(dataset, x, labels, label=0)
print(f"Short GRB: name={short_name}, label=0, t90={short_t90:.4g}")

with pd.option_context("display.max_rows", None):
    display(short_grb)

Short GRB: name=GRB050202, label=0, t90=0.112

     time_index  15-25keV  25-50keV  50-100keV  100-350keV
0             0   -0.0204    0.0219     0.0180     -0.0119
1             1    0.0998    0.1877     0.1782      0.0274
2             2    0.0416    0.1169     0.0870      0.0334
3             3    0.0000    0.0000     0.0000      0.0000
4             4    0.0000    0.0000     0.0000      0.0000
5             5    0.0000    0.0000     0.0000      0.0000
6             6    0.0000    0.0000     0.0000      0.0000
7             7    0.0000    0.0000     0.0000      0.0000
8             8    0.0000    0.0000     0.0000      0.0000
9             9    0.0000    0.0000     0.0000      0.0000
10           10    0.0000    0.0000     0.0000      0.0000
11           11    0.0000    0.0000     0.0000      0.0000
12           12    0.0000    0.0000     0.0000      0.0000
13           13    0.0000    0.0000     0.0000      0.0000
14           14    0.0000    0.0000     0.0000      0.0000
15           15    0.0000    0.0000     0.0000      0.0000
16           16    0.0000    0.0000     0.0000      0.0000
17           17    0.0000    0.0000     0.0000      0.0000
18           18    0.0000    0.0000     0.0000      0.0000
19           19    0.0000    0.0000     0.0000      0.0000
20           20    0.0000    0.0000     0.0000      0.0000
21           21    0.0000    0.0000     0.0000      0.0000
22           22    0.0000    0.0000     0.0000      0.0000
23           23    0.0000    0.0000     0.0000      0.0000
24           24    0.0000    0.0000     0.0000      0.0000
25           25    0.0000    0.0000     0.0000      0.0000
26           26    0.0000    0.0000     0.0000      0.0000
27           27    0.0000    0.0000     0.0000      0.0000
28           28    0.0000    0.0000     0.0000      0.0000
29           29    0.0000    0.0000     0.0000      0.0000
30           30    0.0000    0.0000     0.0000      0.0000
31           31    0.0000    0.0000     0.0000      0.0000
32           32    0.0000    0.0000     0.0000      0.0000
33           33    0.0000    0.0000     0.0000      0.0000
34           34    0.0000    0.0000     0.0000      0.0000
35           35    0.0000    0.0000     0.0000      0.0000
36           36    0.0000    0.0000     0.0000      0.0000
37           37    0.0000    0.0000     0.0000      0.0000
38           38    0.0000    0.0000     0.0000      0.0000
39           39    0.0000    0.0000     0.0000      0.0000
40           40    0.0000    0.0000     0.0000      0.0000
41           41    0.0000    0.0000     0.0000      0.0000
42           42    0.0000    0.0000     0.0000      0.0000
43           43    0.0000    0.0000     0.0000      0.0000
44           44    0.0000    0.0000     0.0000      0.0000
45           45    0.0000    0.0000     0.0000      0.0000
46           46    0.0000    0.0000     0.0000      0.0000
47           47    0.0000    0.0000     0.0000      0.0000
48           48    0.0000    0.0000     0.0000      0.0000
49           49    0.0000    0.0000     0.0000      0.0000
50           50    0.0000    0.0000     0.0000      0.0000
51           51    0.0000    0.0000     0.0000      0.0000
52           52    0.0000    0.0000     0.0000      0.0000
53           53    0.0000    0.0000     0.0000      0.0000
54           54    0.0000    0.0000     0.0000      0.0000
55           55    0.0000    0.0000     0.0000      0.0000
56           56    0.0000    0.0000     0.0000      0.0000
57           57    0.0000    0.0000     0.0000      0.0000
58           58    0.0000    0.0000     0.0000      0.0000
59           59    0.0000    0.0000     0.0000      0.0000
60           60    0.0000    0.0000     0.0000      0.0000
61           61    0.0000    0.0000     0.0000      0.0000
62           62    0.0000    0.0000     0.0000      0.0000
63           63    0.0000    0.0000     0.0000      0.0000
64           64    0.0000    0.0000     0.0000      0.0000
65           65    0.0000    0.0000     0.0000      0.0000
66           66    0.0000    0.0000     0.0000      0.0000
67           67    0.0000    0.0000     0.0000      0.0000
68           68    0.0000    0.0000     0.0000      0.0000
69           69    0.0000    0.0000     0.0000      0.0000
70           70    0.0000    0.0000     0.0000      0.0000
71           71    0.0000    0.0000     0.0000      0.0000
72           72    0.0000    0.0000     0.0000      0.0000
73           73    0.0000    0.0000     0.0000      0.0000
74           74    0.0000    0.0000     0.0000      0.0000
75           75    0.0000    0.0000     0.0000      0.0000
76           76    0.0000    0.0000     0.0000      0.0000
77           77    0.0000    0.0000     0.0000      0.0000
78           78    0.0000    0.0000     0.0000      0.0000
79           79    0.0000    0.0000     0.0000      0.0000
80           80    0.0000    0.0000     0.0000      0.0000
81           81    0.0000    0.0000     0.0000      0.0000
82           82    0.0000    0.0000     0.0000      0.0000
83           83    0.0000    0.0000     0.0000      0.0000
84           84    0.0000    0.0000     0.0000      0.0000
85           85    0.0000    0.0000     0.0000      0.0000
86           86    0.0000    0.0000     0.0000      0.0000
87           87    0.0000    0.0000     0.0000      0.0000
88           88    0.0000    0.0000     0.0000      0.0000
89           89    0.0000    0.0000     0.0000      0.0000
90           90    0.0000    0.0000     0.0000      0.0000
91           91    0.0000    0.0000     0.0000      0.0000
92           92    0.0000    0.0000     0.0000      0.0000
93           93    0.0000    0.0000     0.0000      0.0000
94           94    0.0000    0.0000     0.0000      0.0000
95           95    0.0000    0.0000     0.0000      0.0000
96           96    0.0000    0.0000     0.0000      0.0000
97           97    0.0000    0.0000     0.0000      0.0000
98           98    0.0000    0.0000     0.0000      0.0000
99           99    0.0000    0.0000     0.0000      0.0000
100         100    0.0000    0.0000     0.0000      0.0000
101         101    0.0000    0.0000     0.0000      0.0000
102         102    0.0000    0.0000     0.0000      0.0000
103         103    0.0000    0.0000     0.0000      0.0000
104         104    0.0000    0.0000     0.0000      0.0000
105         105    0.0000    0.0000     0.0000      0.0000
106         106    0.0000    0.0000     0.0000      0.0000
107         107    0.0000    0.0000     0.0000      0.0000
108         108    0.0000    0.0000     0.0000      0.0000
109         109    0.0000    0.0000     0.0000      0.0000
110         110    0.0000    0.0000     0.0000      0.0000
111         111    0.0000    0.0000     0.0000      0.0000
112         112    0.0000    0.0000     0.0000      0.0000
113         113    0.0000    0.0000     0.0000      0.0000
114         114    0.0000    0.0000     0.0000      0.0000
115         115    0.0000    0.0000     0.0000      0.0000
116         116    0.0000    0.0000     0.0000      0.0000
117         117    0.0000    0.0000     0.0000      0.0000
118         118    0.0000    0.0000     0.0000      0.0000
119         119    0.0000    0.0000     0.0000      0.0000
120         120    0.0000    0.0000     0.0000      0.0000
121         121    0.0000    0.0000     0.0000      0.0000
122         122    0.0000    0.0000     0.0000      0.0000
123         123    0.0000    0.0000     0.0000      0.0000
124         124    0.0000    0.0000     0.0000      0.0000
125         125    0.0000    0.0000     0.0000      0.0000
126         126    0.0000    0.0000     0.0000      0.0000
127         127    0.0000    0.0000     0.0000      0.0000
128         128    0.0000    0.0000     0.0000      0.0000
129         129    0.0000    0.0000     0.0000      0.0000
130         130    0.0000    0.0000     0.0000      0.0000
131         131    0.0000    0.0000     0.0000      0.0000
132         132    0.0000    0.0000     0.0000      0.0000
133         133    0.0000    0.0000     0.0000      0.0000
134         134    0.0000    0.0000     0.0000      0.0000
135         135    0.0000    0.0000     0.0000      0.0000
136         136    0.0000    0.0000     0.0000      0.0000
137         137    0.0000    0.0000     0.0000      0.0000
138         138    0.0000    0.0000     0.0000      0.0000
139         139    0.0000    0.0000     0.0000      0.0000
140         140    0.0000    0.0000     0.0000      0.0000
141         141    0.0000    0.0000     0.0000      0.0000
142         142    0.0000    0.0000     0.0000      0.0000
143         143    0.0000    0.0000     0.0000      0.0000
144         144    0.0000    0.0000     0.0000      0.0000
145         145    0.0000    0.0000     0.0000      0.0000
146         146    0.0000    0.0000     0.0000      0.0000
147         147    0.0000    0.0000     0.0000      0.0000
148         148    0.0000    0.0000     0.0000      0.0000
149         149    0.0000    0.0000     0.0000      0.0000
150         150    0.0000    0.0000     0.0000      0.0000
151         151    0.0000    0.0000     0.0000      0.0000
152         152    0.0000    0.0000     0.0000      0.0000
153         153    0.0000    0.0000     0.0000      0.0000
154         154    0.0000    0.0000     0.0000      0.0000
155         155    0.0000    0.0000     0.0000      0.0000
156         156    0.0000    0.0000     0.0000      0.0000
157         157    0.0000    0.0000     0.0000      0.0000
158         158    0.0000    0.0000     0.0000      0.0000
159         159    0.0000    0.0000     0.0000      0.0000
160         160    0.0000    0.0000     0.0000      0.0000
161         161    0.0000    0.0000     0.0000      0.0000
162         162    0.0000    0.0000     0.0000      0.0000
163         163    0.0000    0.0000     0.0000      0.0000
164         164    0.0000    0.0000     0.0000      0.0000
165         165    0.0000    0.0000     0.0000      0.0000
166         166    0.0000    0.0000     0.0000      0.0000
167         167    0.0000    0.0000     0.0000      0.0000
168         168    0.0000    0.0000     0.0000      0.0000
169         169    0.0000    0.0000     0.0000      0.0000
170         170    0.0000    0.0000     0.0000      0.0000
171         171    0.0000    0.0000     0.0000      0.0000
172         172    0.0000    0.0000     0.0000      0.0000
173         173    0.0000    0.0000     0.0000      0.0000
174         174    0.0000    0.0000     0.0000      0.0000
175         175    0.0000    0.0000     0.0000      0.0000
176         176    0.0000    0.0000     0.0000      0.0000
177         177    0.0000    0.0000     0.0000      0.0000
178         178    0.0000    0.0000     0.0000      0.0000
179         179    0.0000    0.0000     0.0000      0.0000
180         180    0.0000    0.0000     0.0000      0.0000
181         181    0.0000    0.0000     0.0000      0.0000
182         182    0.0000    0.0000     0.0000      0.0000
183         183    0.0000    0.0000     0.0000      0.0000
184         184    0.0000    0.0000     0.0000      0.0000
185         185    0.0000    0.0000     0.0000      0.0000
186         186    0.0000    0.0000     0.0000      0.0000
187         187    0.0000    0.0000     0.0000      0.0000
188         188    0.0000    0.0000     0.0000      0.0000
189         189    0.0000    0.0000     0.0000      0.0000
190         190    0.0000    0.0000     0.0000      0.0000
191         191    0.0000    0.0000     0.0000      0.0000
192         192    0.0000    0.0000     0.0000      0.0000
193         193    0.0000    0.0000     0.0000      0.0000
194         194    0.0000    0.0000     0.0000      0.0000
195         195    0.0000    0.0000     0.0000      0.0000
196         196    0.0000    0.0000     0.0000      0.0000
197         197    0.0000    0.0000     0.0000      0.0000
198         198    0.0000    0.0000     0.0000      0.0000
199         199    0.0000    0.0000     0.0000      0.0000
200         200    0.0000    0.0000     0.0000      0.0000
201         201    0.0000    0.0000     0.0000      0.0000
202         202    0.0000    0.0000     0.0000      0.0000
203         203    0.0000    0.0000     0.0000      0.0000
204         204    0.0000    0.0000     0.0000      0.0000
205         205    0.0000    0.0000     0.0000      0.0000
206         206    0.0000    0.0000     0.0000      0.0000
207         207    0.0000    0.0000     0.0000      0.0000
208         208    0.0000    0.0000     0.0000      0.0000
209         209    0.0000    0.0000     0.0000      0.0000
210         210    0.0000    0.0000     0.0000      0.0000
211         211    0.0000    0.0000     0.0000      0.0000
212         212    0.0000    0.0000     0.0000      0.0000
213         213    0.0000    0.0000     0.0000      0.0000
214         214    0.0000    0.0000     0.0000      0.0000
215         215    0.0000    0.0000     0.0000      0.0000
216         216    0.0000    0.0000     0.0000      0.0000
217         217    0.0000    0.0000     0.0000      0.0000
218         218    0.0000    0.0000     0.0000      0.0000
219         219    0.0000    0.0000     0.0000      0.0000
220         220    0.0000    0.0000     0.0000      0.0000
221         221    0.0000    0.0000     0.0000      0.0000
222         222    0.0000    0.0000     0.0000      0.0000
223         223    0.0000    0.0000     0.0000      0.0000
224         224    0.0000    0.0000     0.0000      0.0000
225         225    0.0000    0.0000     0.0000      0.0000
226         226    0.0000    0.0000     0.0000      0.0000
227         227    0.0000    0.0000     0.0000      0.0000
228         228    0.0000    0.0000     0.0000      0.0000
229         229    0.0000    0.0000     0.0000      0.0000
230         230    0.0000    0.0000     0.0000      0.0000
231         231    0.0000    0.0000     0.0000      0.0000
232         232    0.0000    0.0000     0.0000      0.0000
233         233    0.0000    0.0000     0.0000      0.0000
234         234    0.0000    0.0000     0.0000      0.0000
235         235    0.0000    0.0000     0.0000      0.0000
236         236    0.0000    0.0000     0.0000      0.0000
237         237    0.0000    0.0000     0.0000      0.0000
238         238    0.0000    0.0000     0.0000      0.0000
239         239    0.0000    0.0000     0.0000      0.0000
240         240    0.0000    0.0000     0.0000      0.0000
241         241    0.0000    0.0000     0.0000      0.0000
242         242    0.0000    0.0000     0.0000      0.0000
243         243    0.0000    0.0000     0.0000      0.0000
244         244    0.0000    0.0000     0.0000      0.0000
245         245    0.0000    0.0000     0.0000      0.0000
246         246    0.0000    0.0000     0.0000      0.0000
247         247    0.0000    0.0000     0.0000      0.0000
248         248    0.0000    0.0000     0.0000      0.0000
249         249    0.0000    0.0000     0.0000      0.0000
250         250    0.0000    0.0000     0.0000      0.0000
251         251    0.0000    0.0000     0.0000      0.0000
252         252    0.0000    0.0000     0.0000      0.0000
253         253    0.0000    0.0000     0.0000      0.0000
254         254    0.0000    0.0000     0.0000      0.0000
255         255    0.0000    0.0000     0.0000      0.0000
256         256    0.0000    0.0000     0.0000      0.0000
257         257    0.0000    0.0000     0.0000      0.0000
258         258    0.0000    0.0000     0.0000      0.0000
259         259    0.0000    0.0000     0.0000      0.0000
260         260    0.0000    0.0000     0.0000      0.0000
261         261    0.0000    0.0000     0.0000      0.0000
262         262    0.0000    0.0000     0.0000      0.0000
263         263    0.0000    0.0000     0.0000      0.0000
264         264    0.0000    0.0000     0.0000      0.0000
265         265    0.0000    0.0000     0.0000      0.0000
266         266    0.0000    0.0000     0.0000      0.0000
267         267    0.0000    0.0000     0.0000      0.0000
268         268    0.0000    0.0000     0.0000      0.0000
269         269    0.0000    0.0000     0.0000      0.0000
270         270    0.0000    0.0000     0.0000      0.0000
271         271    0.0000    0.0000     0.0000      0.0000
272         272    0.0000    0.0000     0.0000      0.0000
273         273    0.0000    0.0000     0.0000      0.0000
274         274    0.0000    0.0000     0.0000      0.0000
275         275    0.0000    0.0000     0.0000      0.0000
276         276    0.0000    0.0000     0.0000      0.0000
277         277    0.0000    0.0000     0.0000      0.0000
278         278    0.0000    0.0000     0.0000      0.0000
279         279    0.0000    0.0000     0.0000      0.0000
280         280    0.0000    0.0000     0.0000      0.0000
281         281    0.0000    0.0000     0.0000      0.0000
282         282    0.0000    0.0000     0.0000      0.0000
283         283    0.0000    0.0000     0.0000      0.0000
284         284    0.0000    0.0000     0.0000      0.0000
285         285    0.0000    0.0000     0.0000      0.0000
286         286    0.0000    0.0000     0.0000      0.0000
287         287    0.0000    0.0000     0.0000      0.0000
288         288    0.0000    0.0000     0.0000      0.0000
289         289    0.0000    0.0000     0.0000      0.0000
290         290    0.0000    0.0000     0.0000      0.0000
291         291    0.0000    0.0000     0.0000      0.0000
292         292    0.0000    0.0000     0.0000      0.0000
293         293    0.0000    0.0000     0.0000      0.0000
294         294    0.0000    0.0000     0.0000      0.0000
295         295    0.0000    0.0000     0.0000      0.0000
296         296    0.0000    0.0000     0.0000      0.0000
297         297    0.0000    0.0000     0.0000      0.0000
298         298    0.0000    0.0000     0.0000      0.0000
299         299    0.0000    0.0000     0.0000      0.0000
300         300    0.0000    0.0000     0.0000      0.0000
301         301    0.0000    0.0000     0.0000      0.0000
302         302    0.0000    0.0000     0.0000      0.0000
303         303    0.0000    0.0000     0.0000      0.0000
304         304    0.0000    0.0000     0.0000      0.0000
305         305    0.0000    0.0000     0.0000      0.0000
306         306    0.0000    0.0000     0.0000      0.0000
307         307    0.0000    0.0000     0.0000      0.0000
308         308    0.0000    0.0000     0.0000      0.0000
309         309    0.0000    0.0000     0.0000      0.0000
310         310    0.0000    0.0000     0.0000      0.0000
311         311    0.0000    0.0000     0.0000      0.0000
312         312    0.0000    0.0000     0.0000      0.0000

## Full long GRB example

In [86]:
long_name, long_t90, long_grb = full_grb_dataframe(dataset, x, labels, label=1)
print(f"Long GRB: name={long_name}, label=1, t90={long_t90:.4g}")

with pd.option_context("display.max_rows", None):
    display(long_grb)

Long GRB: name=GRB041217, label=1, t90=5.668

     time_index  15-25keV  25-50keV  50-100keV  100-350keV
0             0   -0.0350    0.0133    -0.0239     -0.0900
1             1    0.0201    0.0093     0.0516     -0.0400
2             2   -0.0378    0.0997     0.1070      0.0871
3             3    0.0406    0.0368    -0.0109      0.0262
4             4    0.0477    0.0592     0.0537      0.0237
5             5   -0.1250    0.1725    -0.1297      0.0208
6             6    0.0488    0.0504     0.0733      0.0359
7             7   -0.1107    0.0795     0.1080     -0.0065
8             8    0.0203    0.0150     0.0604      0.0586
9             9   -0.0399    0.0270     0.1063      0.0050
10           10    0.0499    0.0279    -0.0004     -0.0450
11           11   -0.0281    0.0197     0.0298      0.0599
12           12    0.0409   -0.0082    -0.0150      0.0176
13           13   -0.0574   -0.0545    -0.0342     -0.0435
14           14    0.0050    0.0930     0.0419      0.0114
15           15    0.0000   -0.0672     0.0121      0.0322
16           16    0.0105    0.0792     0.1684     -0.0661
17           17    0.0494    0.0633     0.1160      0.0087
18           18    0.0004    0.0106     0.0764     -0.0734
19           19    0.0292   -0.0204     0.0324     -0.0223
20           20    0.1332    0.0208    -0.0689     -0.0569
21           21   -0.0094    0.1458     0.0324      0.0123
22           22    0.0065    0.0063     0.0490      0.0090
23           23   -0.0240    0.0330    -0.0358     -0.0030
24           24    0.0161    0.1451    -0.0290      0.0602
25           25   -0.0108    0.0036     0.1265      0.0409
26           26    0.0457    0.1221     0.0950      0.1023
27           27   -0.0018    0.1100     0.0810      0.0114
28           28   -0.0412    0.0490    -0.0024      0.0050
29           29    0.2187    0.1330     0.0332     -0.0069
30           30    0.0970    0.1421     0.1061     -0.0309
31           31    0.0265    0.1597     0.0994      0.0268
32           32   -0.0944    0.1247     0.1061     -0.0120
33           33    0.0309    0.2390    -0.0068      0.1503
34           34    0.0120    0.0167     0.2148     -0.0029
35           35    0.0049    0.1406     0.1368      0.0034
36           36   -0.0567    0.1032     0.0803     -0.0277
37           37    0.0202    0.1967     0.0852      0.1404
38           38    0.1012    0.1701     0.1871      0.0542
39           39    0.0939    0.1248     0.2673     -0.0330
40           40    0.0202    0.1040    -0.0249      0.0007
41           41    0.0296    0.2250     0.0301      0.0280
42           42    0.1437    0.1936     0.1858      0.0594
43           43   -0.0450    0.2028     0.1542      0.1031
44           44    0.1212    0.1253     0.1468      0.0087
45           45    0.1407    0.1022     0.1940      0.0319
46           46    0.0865    0.1688     0.2347      0.1357
47           47    0.1637    0.3014     0.2545     -0.0332
48           48    0.2075    0.2149     0.1236      0.0514
49           49    0.0129    0.2986     0.1255     -0.0492
50           50    0.1318    0.1298     0.3728      0.0881
51           51    0.0717    0.3059     0.2166      0.0424
52           52    0.1431    0.3315     0.3649      0.0540
53           53    0.0434    0.2037     0.2611      0.0556
54           54    0.1253    0.3856     0.1871      0.0497
55           55    0.1578    0.1002     0.1112     -0.0516
56           56    0.1156    0.1717     0.2648      0.0627
57           57    0.1124    0.3431     0.1933     -0.0169
58           58    0.1143    0.2141     0.2237      0.0831
59           59    0.1443    0.2626     0.2981      0.0303
60           60    0.2178    0.2384     0.2514      0.0500
61           61    0.0940    0.3597     0.3149      0.0486
62           62    0.0136    0.2760     0.3678      0.0733
63           63    0.2048    0.0893     0.3251      0.0519
64           64    0.0962    0.5027     0.3430      0.0513
65           65    0.1006    0.2071     0.3437      0.0611
66           66    0.1482    0.2978     0.1798      0.0349
67           67    0.2290    0.3019     0.2695     -0.0234
68           68    0.1687    0.1920     0.4174      0.0748
69           69    0.1487    0.4038     0.2518      0.1435
70           70    0.1126    0.3242     0.3199      0.0715
71           71    0.0805    0.2314     0.1973      0.1665
72           72    0.1857    0.3132     0.3083      0.0072
73           73    0.1659    0.2021     0.2764      0.0823
74           74    0.2039    0.2026     0.2279     -0.0158
75           75    0.0588    0.2285     0.1914      0.0586
76           76    0.2612    0.1648     0.3057      0.0029
77           77    0.1236    0.2160     0.2519      0.1200
78           78    0.0967    0.2228     0.2026      0.0554
79           79    0.0372    0.1904     0.2352      0.0664
80           80    0.0657    0.2193     0.2409      0.0879
81           81    0.1007    0.2969     0.2369      0.0736
82           82    0.2176    0.3326     0.2520      0.0377
83           83    0.2657    0.2327     0.1872      0.0561
84           84    0.1884    0.3371     0.2287     -0.0101
85           85    0.1712    0.2550     0.2487      0.1181
86           86    0.1329    0.1548     0.2094      0.0396
87           87    0.1904    0.1659     0.2884      0.0084
88           88    0.2752    0.3487     0.2873      0.2121
89           89    0.2250    0.2374     0.3118      0.0329
90           90    0.1612    0.3298     0.2405      0.1538
91           91    0.1991    0.1733     0.2456      0.1065
92           92    0.0599    0.3472     0.3652      0.1539
93           93    0.1764    0.3202     0.2550      0.0205
94           94    0.1345    0.2318     0.1331      0.0160
95           95    0.0698    0.3578     0.2053      0.0701
96           96    0.0961    0.2936     0.3128      0.0037
97           97    0.2693    0.3056     0.2813      0.0094
98           98    0.2110    0.2569     0.2452      0.0103
99           99    0.0928    0.2906     0.2051      0.0096
100         100    0.1753    0.3189     0.1600      0.0941
101         101    0.1469    0.3281     0.2115      0.0072
102         102    0.1239    0.2456     0.2276      0.0479
103         103    0.0594    0.2397     0.1894      0.0444
104         104    0.0572    0.2654     0.1193      0.0930
105         105    0.1144    0.2102     0.2116      0.1271
106         106    0.1992    0.1533     0.2745      0.0504
107         107    0.1410    0.1925     0.1764      0.0454
108         108    0.1521    0.3486     0.1349      0.1504
109         109    0.0862    0.1931     0.2558     -0.0638
110         110    0.2098    0.2264     0.2862      0.0972
111         111    0.1662    0.1798     0.2985     -0.0421
112         112    0.1036    0.2001     0.1939     -0.0719
113         113    0.1796    0.2666     0.1266     -0.0050
114         114    0.1267    0.2264     0.1729     -0.0139
115         115    0.1663    0.1298     0.1709      0.1950
116         116    0.1203    0.2856     0.1661     -0.0139
117         117    0.1580    0.2157     0.1953     -0.0079
118         118    0.1176    0.2356     0.1274      0.0321
119         119    0.1455    0.2805     0.1688      0.0791
120         120    0.1662    0.2627     0.1260      0.0853
121         121    0.1503    0.3126     0.1958      0.0731
122         122    0.0913    0.2050     0.0571      0.0897
123         123    0.2405    0.0686     0.1533      0.0071
124         124    0.1770    0.1345     0.1003      0.0677
125         125    0.1010    0.1659     0.0761      0.0109
126         126    0.0872    0.3875     0.0243      0.0110
127         127    0.1444    0.2315     0.0635      0.0838
128         128    0.0942    0.0283     0.1845      0.0089
129         129    0.0958    0.2071     0.1074     -0.0524
130         130    0.0682    0.1875     0.1233     -0.0645
131         131    0.1821    0.1665     0.1099      0.0110
132         132    0.0337    0.1744     0.0761     -0.0281
133         133    0.1803    0.1169     0.0094     -0.0599
134         134    0.0723    0.0748     0.1171      0.0246
135         135    0.0694    0.1068     0.1242     -0.0198
136         136    0.1672    0.0746    -0.0226      0.0331
137         137    0.1818    0.0957     0.1473     -0.0282
138         138   -0.0127    0.1010    -0.0180      0.0905
139         139   -0.0036    0.1777     0.1043     -0.0387
140         140   -0.0510   -0.0012     0.0508      0.1002
141         141    0.0912    0.1803     0.0424     -0.0427
142         142    0.1205    0.0846     0.0483     -0.0115
143         143    0.0524    0.0760     0.1878      0.0571
144         144    0.0686    0.1863     0.1067      0.0177
145         145   -0.0369    0.0840     0.0073      0.0179
146         146    0.0056    0.1921    -0.0319      0.0562
147         147    0.1812   -0.0204     0.1487      0.0124
148         148   -0.0120    0.1058    -0.0113     -0.0172
149         149    0.0896    0.0926     0.0832     -0.0212
150         150    0.0702    0.1430     0.0335     -0.0343
151         151    0.0934    0.0854     0.0691      0.0833
152         152    0.1671    0.2215     0.1754      0.0318
153         153    0.0376    0.0584    -0.0789     -0.0019
154         154    0.1225    0.1550     0.0143      0.1217
155         155   -0.0396   -0.0326     0.0699      0.0366
156         156    0.0636    0.1880     0.0680     -0.0484
157         157    0.0881    0.0938     0.0020     -0.0361
158         158    0.0169    0.0347     0.0264     -0.0083
159         159    0.0526    0.2088     0.0737      0.0169
160         160    0.0352    0.0590    -0.0718      0.0325
161         161    0.1515    0.0133    -0.0028     -0.0629
162         162   -0.0448    0.1450     0.0255     -0.0867
163         163    0.0860    0.0819     0.0005     -0.0030
164         164    0.2061    0.0146     0.0587      0.0631
165         165   -0.0617    0.0868    -0.0410      0.0088
166         166   -0.1051    0.0483    -0.0049     -0.0880
167         167    0.1123   -0.0231     0.0309     -0.0357
168         168    0.0744    0.0341     0.0201      0.0242
169         169    0.0656    0.0722     0.0044     -0.0208
170         170   -0.0851    0.0720     0.0137      0.1069
171         171    0.1435   -0.0227     0.0681      0.0402
172         172   -0.0096    0.1294     0.1305      0.0033
173         173   -0.0546   -0.0262    -0.0032      0.0602
174         174    0.1542    0.0741    -0.0425      0.0255
175         175    0.1949   -0.0156     0.1180      0.0440
176         176    0.1022    0.0689    -0.0324      0.0077
177         177    0.0000    0.0000     0.0000      0.0000
178         178    0.0000    0.0000     0.0000      0.0000
179         179    0.0000    0.0000     0.0000      0.0000
180         180    0.0000    0.0000     0.0000      0.0000
181         181    0.0000    0.0000     0.0000      0.0000
182         182    0.0000    0.0000     0.0000      0.0000
183         183    0.0000    0.0000     0.0000      0.0000
184         184    0.0000    0.0000     0.0000      0.0000
185         185    0.0000    0.0000     0.0000      0.0000
186         186    0.0000    0.0000     0.0000      0.0000
187         187    0.0000    0.0000     0.0000      0.0000
188         188    0.0000    0.0000     0.0000      0.0000
189         189    0.0000    0.0000     0.0000      0.0000
190         190    0.0000    0.0000     0.0000      0.0000
191         191    0.0000    0.0000     0.0000      0.0000
192         192    0.0000    0.0000     0.0000      0.0000
193         193    0.0000    0.0000     0.0000      0.0000
194         194    0.0000    0.0000     0.0000      0.0000
195         195    0.0000    0.0000     0.0000      0.0000
196         196    0.0000    0.0000     0.0000      0.0000
197         197    0.0000    0.0000     0.0000      0.0000
198         198    0.0000    0.0000     0.0000      0.0000
199         199    0.0000    0.0000     0.0000      0.0000
200         200    0.0000    0.0000     0.0000      0.0000
201         201    0.0000    0.0000     0.0000      0.0000
202         202    0.0000    0.0000     0.0000      0.0000
203         203    0.0000    0.0000     0.0000      0.0000
204         204    0.0000    0.0000     0.0000      0.0000
205         205    0.0000    0.0000     0.0000      0.0000
206         206    0.0000    0.0000     0.0000      0.0000
207         207    0.0000    0.0000     0.0000      0.0000
208         208    0.0000    0.0000     0.0000      0.0000
209         209    0.0000    0.0000     0.0000      0.0000
210         210    0.0000    0.0000     0.0000      0.0000
211         211    0.0000    0.0000     0.0000      0.0000
212         212    0.0000    0.0000     0.0000      0.0000
213         213    0.0000    0.0000     0.0000      0.0000
214         214    0.0000    0.0000     0.0000      0.0000
215         215    0.0000    0.0000     0.0000      0.0000
216         216    0.0000    0.0000     0.0000      0.0000
217         217    0.0000    0.0000     0.0000      0.0000
218         218    0.0000    0.0000     0.0000      0.0000
219         219    0.0000    0.0000     0.0000      0.0000
220         220    0.0000    0.0000     0.0000      0.0000
221         221    0.0000    0.0000     0.0000      0.0000
222         222    0.0000    0.0000     0.0000      0.0000
223         223    0.0000    0.0000     0.0000      0.0000
224         224    0.0000    0.0000     0.0000      0.0000
225         225    0.0000    0.0000     0.0000      0.0000
226         226    0.0000    0.0000     0.0000      0.0000
227         227    0.0000    0.0000     0.0000      0.0000
228         228    0.0000    0.0000     0.0000      0.0000
229         229    0.0000    0.0000     0.0000      0.0000
230         230    0.0000    0.0000     0.0000      0.0000
231         231    0.0000    0.0000     0.0000      0.0000
232         232    0.0000    0.0000     0.0000      0.0000
233         233    0.0000    0.0000     0.0000      0.0000
234         234    0.0000    0.0000     0.0000      0.0000
235         235    0.0000    0.0000     0.0000      0.0000
236         236    0.0000    0.0000     0.0000      0.0000
237         237    0.0000    0.0000     0.0000      0.0000
238         238    0.0000    0.0000     0.0000      0.0000
239         239    0.0000    0.0000     0.0000      0.0000
240         240    0.0000    0.0000     0.0000      0.0000
241         241    0.0000    0.0000     0.0000      0.0000
242         242    0.0000    0.0000     0.0000      0.0000
243         243    0.0000    0.0000     0.0000      0.0000
244         244    0.0000    0.0000     0.0000      0.0000
245         245    0.0000    0.0000     0.0000      0.0000
246         246    0.0000    0.0000     0.0000      0.0000
247         247    0.0000    0.0000     0.0000      0.0000
248         248    0.0000    0.0000     0.0000      0.0000
249         249    0.0000    0.0000     0.0000      0.0000
250         250    0.0000    0.0000     0.0000      0.0000
251         251    0.0000    0.0000     0.0000      0.0000
252         252    0.0000    0.0000     0.0000      0.0000
253         253    0.0000    0.0000     0.0000      0.0000
254         254    0.0000    0.0000     0.0000      0.0000
255         255    0.0000    0.0000     0.0000      0.0000
256         256    0.0000    0.0000     0.0000      0.0000
257         257    0.0000    0.0000     0.0000      0.0000
258         258    0.0000    0.0000     0.0000      0.0000
259         259    0.0000    0.0000     0.0000      0.0000
260         260    0.0000    0.0000     0.0000      0.0000
261         261    0.0000    0.0000     0.0000      0.0000
262         262    0.0000    0.0000     0.0000      0.0000
263         263    0.0000    0.0000     0.0000      0.0000
264         264    0.0000    0.0000     0.0000      0.0000
265         265    0.0000    0.0000     0.0000      0.0000
266         266    0.0000    0.0000     0.0000      0.0000
267         267    0.0000    0.0000     0.0000      0.0000
268         268    0.0000    0.0000     0.0000      0.0000
269         269    0.0000    0.0000     0.0000      0.0000
270         270    0.0000    0.0000     0.0000      0.0000
271         271    0.0000    0.0000     0.0000      0.0000
272         272    0.0000    0.0000     0.0000      0.0000
273         273    0.0000    0.0000     0.0000      0.0000
274         274    0.0000    0.0000     0.0000      0.0000
275         275    0.0000    0.0000     0.0000      0.0000
276         276    0.0000    0.0000     0.0000      0.0000
277         277    0.0000    0.0000     0.0000      0.0000
278         278    0.0000    0.0000     0.0000      0.0000
279         279    0.0000    0.0000     0.0000      0.0000
280         280    0.0000    0.0000     0.0000      0.0000
281         281    0.0000    0.0000     0.0000      0.0000
282         282    0.0000    0.0000     0.0000      0.0000
283         283    0.0000    0.0000     0.0000      0.0000
284         284    0.0000    0.0000     0.0000      0.0000
285         285    0.0000    0.0000     0.0000      0.0000
286         286    0.0000    0.0000     0.0000      0.0000
287         287    0.0000    0.0000     0.0000      0.0000
288         288    0.0000    0.0000     0.0000      0.0000
289         289    0.0000    0.0000     0.0000      0.0000
290         290    0.0000    0.0000     0.0000      0.0000
291         291    0.0000    0.0000     0.0000      0.0000
292         292    0.0000    0.0000     0.0000      0.0000
293         293    0.0000    0.0000     0.0000      0.0000
294         294    0.0000    0.0000     0.0000      0.0000
295         295    0.0000    0.0000     0.0000      0.0000
296         296    0.0000    0.0000     0.0000      0.0000
297         297    0.0000    0.0000     0.0000      0.0000
298         298    0.0000    0.0000     0.0000      0.0000
299         299    0.0000    0.0000     0.0000      0.0000
300         300    0.0000    0.0000     0.0000      0.0000
301         301    0.0000    0.0000     0.0000      0.0000
302         302    0.0000    0.0000     0.0000      0.0000
303         303    0.0000    0.0000     0.0000      0.0000
304         304    0.0000    0.0000     0.0000      0.0000
305         305    0.0000    0.0000     0.0000      0.0000
306         306    0.0000    0.0000     0.0000      0.0000
307         307    0.0000    0.0000     0.0000      0.0000
308         308    0.0000    0.0000     0.0000      0.0000
309         309    0.0000    0.0000     0.0000      0.0000
310         310    0.0000    0.0000     0.0000      0.0000
311         311    0.0000    0.0000     0.0000      0.0000
312         312    0.0000    0.0000     0.0000      0.0000

## T90 summary by class

In [87]:
t90_summary(labels, t90)

   class   mean    std  median    min    q25    q75     max
0  short 0.5541 0.4839  0.3840 0.0120 0.1800 0.8250  2.0000
1   long 5.9119 2.2997  6.0320 2.0920 3.9270 7.7680 10.0000

## Overall light-curve summary by class

In [88]:
overall_signal_summary(x, labels)

   class  all_values_mean  all_values_std  per_grb_mean  per_grb_peak_mean  per_grb_sum_mean  zero_fraction
0  short           0.0023          0.0324        0.0023             0.3615            2.8410         0.9471
1   long           0.0188          0.1421        0.0188             0.4080           23.5707         0.5176

## Average values across bands by class

In [89]:
bands = band_summary(x, labels, dataset.channel_columns)
bands

   class        band  timepoint_mean  timepoint_std  per_grb_mean_avg  per_grb_peak_avg  per_grb_sum_avg  zero_fraction
0  short    15-25keV          0.0019         0.0263            0.0019            0.1932           0.6033         0.9470
1  short    25-50keV          0.0031         0.0378            0.0031            0.3029           0.9818         0.9470
2  short   50-100keV          0.0030         0.0397            0.0030            0.3120           0.9399         0.9470
3  short  100-350keV          0.0010         0.0221            0.0010            0.1679           0.3160         0.9473
4   long    15-25keV          0.0213         0.1588            0.0213            0.2992           6.6691         0.5173
5   long    25-50keV          0.0284         0.1886            0.0284            0.3691           8.8896         0.5174
6   long   50-100keV          0.0206         0.1316            0.0206            0.3221           6.4361         0.5176
7   long  100-350keV          0.0050         0.0482            0.0050            0.1829           1.5760         0.5181

## Long versus short differences by band

In [90]:
short_long_difference(bands)

,band,timepoint_mean_long_minus_short,timepoint_mean_long_div_short,timepoint_std_long_minus_short,timepoint_std_long_div_short,per_grb_mean_avg_long_minus_short,per_grb_mean_avg_long_div_short,per_grb_peak_avg_long_minus_short,per_grb_peak_avg_long_div_short,per_grb_sum_avg_long_minus_short,per_grb_sum_avg_long_div_short,zero_fraction_long_minus_short,zero_fraction_long_div_short
0,15-25keV,0.0194,11.0546,0.1325,6.0347,0.0194,11.0546,0.1060,1.5486,6.0658,11.0546,-0.4297,0.5463
1,25-50keV,0.0253,9.0546,0.1508,4.9912,0.0253,9.0546,0.0662,1.2185,7.9078,9.0546,-0.4295,0.5464
2,50-100keV,0.0176,6.8475,0.0918,3.3111,0.0176,6.8475,0.0101,1.0323,5.4962,6.8475,-0.4294,0.5466
3,100-350keV,0.0040,4.9866,0.0260,2.1770,0.0040,4.9866,0.0150,1.0893,1.2600,4.9866,-0.4292,0.5469